services:
  - type: web
    name: vss-cloud-server
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
    autoDeploy: false

databases:
  - name: vss-db
    plan: free
    ipAllowList: [] # Allow all
